/*
  Drop all tables from database
*/

SELECT 
	'DROP TABLE [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']' 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE';

/*
  Drop all stored procedures from database
*/

SELECT 
	'DROP PROCEDURE [' + ROUTINE_NAME + ']' 
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE = 'PROCEDURE';

/*
  Drop all FK from dabase
*/

SELECT DISTINCT 
	'ALTER TABLE [' + KF.TABLE_NAME + '] DROP CONSTRAINT [' + RC.CONSTRAINT_NAME + ']'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KF 
	ON RC.CONSTRAINT_NAME = KF.CONSTRAINT_NAME
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KP 
	ON RC.UNIQUE_CONSTRAINT_NAME = KP.CONSTRAINT_NAME;;
